config/routes.rb
Rails.application.routes.draw do
  root 'gists#index'

  resources :gists do
    resources :comments
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gist
end

app/models/gist.rb
class Gist < ApplicationRecord
  has_many :comments

  validates :src, presence: true, length: { minimum: 8, maximum: 256 }
  validates :lang, presence: true, length: { maximum: 16 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @gist = Gist.find(params[:gist_id])
    @comment = @gist.comments.create(comment_params)
    redirect_to gist_path(@gist)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :set_gist, only: [:show, :edit, :update, :destroy]

  # GET /gists
  # GET /gists.json
  def index
    @gists = Gist.all
  end

  # GET /gists/1
  # GET /gists/1.json
  def show
  end

  # GET /gists/new
  def new
    @gist = Gist.new
  end

  # GET /gists/1/edit
  def edit
  end

  # POST /gists
  # POST /gists.json
  def create
    @gist = Gist.new(gist_params)

    respond_to do |format|
      if @gist.save
        format.html { redirect_to @gist, notice: 'Gist was successfully created.' }
        format.json { render :show, status: :created, location: @gist }
      else
        format.html { render :new }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gists/1
  # PATCH/PUT /gists/1.json
  def update
    respond_to do |format|
      if @gist.update(gist_params)
        format.html { redirect_to @gist, notice: 'Gist was successfully updated.' }
        format.json { render :show, status: :ok, location: @gist }
      else
        format.html { render :edit }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gists/1
  # DELETE /gists/1.json
  def destroy
    @gist.destroy
    respond_to do |format|
      format.html { redirect_to gists_url, notice: 'Gist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_gist
    @gist = Gist.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def gist_params
    params.require(:gist).permit(:src, :lang, :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/views/comments/_comment.html.erb
<p><strong>Commenter:</strong> <%= comment.commenter %></p>
<p><strong>Comment:</strong> <%= comment.body %></p>

app/views/comments/_form.html.erb
<%= form_with(model: [@gist, @gist.comments.build], local: true) do |form| %>
  <p><%= form.label :commenter %>: <%= form.text_field :commenter %></p>
  <p><%= form.label :body %>: <%= form.text_area :body %></p>
  <p><%= form.submit %></p>
<% end %>

app/views/gists/_form.html.erb
<%= bootstrap_form_with(model: @gist, local: true) do |f| %>
  <%= f.text_area :src %>
  <%= f.text_field :lang %>
  <%= f.text_field :desc %>
  <%= f.submit %>
<% end %>

app/views/gists/_gist.html.erb
<pre><%= gist.src[0..40] + '…' %></pre>
<p>Lang: <%= gist.lang %></p>
<p>Desc: <%= gist.desc %></p>
<p>
  <%= link_to 'Show', gist %> |
  <%= link_to 'Edit', edit_gist_path(gist) %> |
  <%= link_to 'Destroy', gist, method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

app/views/gists/edit.html.erb
<h1>Editing Gist</h1>

<%= render 'form', gist: @gist %>

<%= link_to 'Show', @gist %> |
<%= link_to 'Back', gists_path %>

app/views/gists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gists</h1>
<%= render @gists %>

<br>

<%= link_to 'New Gist', new_gist_path %>

app/views/gists/new.html.erb
<h1>New Gist</h1>

<%= render 'form', gist: @gist %>

<%= link_to 'Back', gists_path %>

app/views/gists/show.html.erb
<p id="notice"><%= notice %></p>

<pre class="highlight"><%= raw Rouge.highlight @gist.src, @gist.lang, 'html' %></pre>
<p><strong>Lang:</strong> <%= @gist.lang %></p>
<p><strong>Desc:</strong> <%= @gist.desc %></p>

<h2>Comments</h2>
<%= render @gist.comments %>

<h2>Add a comment</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_gist_path(@gist) %> |
<%= link_to 'Back', gists_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# add navigation links to this file %>
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "My Gists 5.2 (Bootstrap 4)" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "My Gists 5.2" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main" class="container">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>